### ISSUE TITLE
Make the docker base image configurable

### ISSUE THREAD

**Issue by Yolgie** [natiginfo/action-detekt-all#66]
Hi,
The current docker base image you use is: openjdk:jre-slim (https://hub.docker.com/layers/library/openjdk/jre-slim/images/sha256-85b8cdf35cb48bce5d6f6e69d5580af76141a6ba752beb9b9e817d97401bfc22) which contains debian/openjdk-11-jre-headless.

Would it be possible to add a param to the github action to use a more current image like: amazoncorretto:latest or eclipse-temurin:latest

**Comment by natiginfo** [comment]
v3 adds exactly this. `java-distribution` and `java-version` are now required inputs, so you can use whatever distribution you need:

```yaml
- uses: natiginfo/action-detekt-all@v3
  with:
    detekt-version: '2.0.0-alpha.3'
    java-distribution: 'corretto'
    java-version: '17'
```

Any distribution supported by [actions/setup-java](https://github.com/actions/setup-java#supported-distributions) works. Could you give it a try?
